name: CI

on: [push]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'

      - name: Test
        run: ./gradlew test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Publish to Bintray
        if: github.ref == 'refs/heads/release'
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew bintrayUpload && ./gradlew bintrayPublish
